remote_theme: jekyll/minima
title: Bioinformatics Guide
description: CuSTOM and Developmental Biology @ CCHMC
header_pages:
   - faq.md
   - reviews/reviews.md
   - tutorials/tutorials.md
plugins:
  - jekyll-seo-tag 
minima:
  skin: auto
