remote_theme: jekyll/minima
title: Bioinformatics Guide
description: CuSTOM and Developmental Biology @ CCHMC
header_pages:
   - reviews/reviews.md
   - tutorials.md
plugins:
  - jekyll-seo-tag