remote_theme: jekyll/minima
title: Bioinformatics Guide
description: CCHMC - CuSTOM and Developmental Biology
header_pages:
   - reviews/reviews.md
   - tutorials/tutorials.md
plugins:
  - jekyll-seo-tag